name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 21.5.0
    - name: Checkout TS
      uses: actions/checkout@v2
      with:
        path: ts
    - name: Checkout Models
      uses: actions/checkout@v2
      with:
        repository: masagroup/soft.models
        ref: e838fd4e52b49f03ec99ad86a9d3a10f39f30a3c
        path: models
    - name: Build and Test
      working-directory: ts
      run: sudo make ci
    
