name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.5.1
    - name: Checkout TS
      uses: actions/checkout@v4
      with:
        path: ts
    - name: Checkout Models
      uses: actions/checkout@v4
      with:
        repository: masagroup/soft.models
        ref: f0dd72e4ff1ff931f202c7464d30a15b4cf2102d
        path: models
    - name: Build and Test
      working-directory: ts
      run: sudo make ci
    
